-- Catálogos mínimos para conversaciones y participantes del chat.
-- Requiere las tablas CONVERSATIONS_STATUSES y SENDER_TYPES.
-- Los IDs de Abierta y Cliente coinciden con Agent__InitialConversationStatusId
-- y Agent__ClientParticipantTypeId.
SET DEFINE OFF;

MERGE INTO CONVERSATIONS_STATUSES target
USING (SELECT '81000000-0000-0000-0000-000000000001' ID, 'Abierta' NAME FROM DUAL) source
ON (target.CONVERSATIONS_STATUSES_ID = source.ID)
WHEN MATCHED THEN UPDATE SET target.NAME_STATUS = source.NAME
WHEN NOT MATCHED THEN
    INSERT (CONVERSATIONS_STATUSES_ID, NAME_STATUS, CREATED_AT)
    VALUES (source.ID, source.NAME, SYSTIMESTAMP);

MERGE INTO CONVERSATIONS_STATUSES target
USING (SELECT '81000000-0000-0000-0000-000000000002' ID, 'En atención' NAME FROM DUAL) source
ON (target.CONVERSATIONS_STATUSES_ID = source.ID)
WHEN MATCHED THEN UPDATE SET target.NAME_STATUS = source.NAME
WHEN NOT MATCHED THEN
    INSERT (CONVERSATIONS_STATUSES_ID, NAME_STATUS, CREATED_AT)
    VALUES (source.ID, source.NAME, SYSTIMESTAMP);

MERGE INTO CONVERSATIONS_STATUSES target
USING (SELECT '81000000-0000-0000-0000-000000000003' ID, 'Escalada' NAME FROM DUAL) source
ON (target.CONVERSATIONS_STATUSES_ID = source.ID)
WHEN MATCHED THEN UPDATE SET target.NAME_STATUS = source.NAME
WHEN NOT MATCHED THEN
    INSERT (CONVERSATIONS_STATUSES_ID, NAME_STATUS, CREATED_AT)
    VALUES (source.ID, source.NAME, SYSTIMESTAMP);

MERGE INTO CONVERSATIONS_STATUSES target
USING (SELECT '81000000-0000-0000-0000-000000000004' ID, 'Cerrada' NAME FROM DUAL) source
ON (target.CONVERSATIONS_STATUSES_ID = source.ID)
WHEN MATCHED THEN UPDATE SET target.NAME_STATUS = source.NAME
WHEN NOT MATCHED THEN
    INSERT (CONVERSATIONS_STATUSES_ID, NAME_STATUS, CREATED_AT)
    VALUES (source.ID, source.NAME, SYSTIMESTAMP);

MERGE INTO SENDER_TYPES target
USING (SELECT '82000000-0000-0000-0000-000000000001' ID, 'Cliente' NAME FROM DUAL) source
ON (target.SENDER_TYPES_ID = source.ID)
WHEN MATCHED THEN UPDATE SET target.NAME_TYPE = source.NAME
WHEN NOT MATCHED THEN
    INSERT (SENDER_TYPES_ID, NAME_TYPE, CREATED_AT)
    VALUES (source.ID, source.NAME, SYSTIMESTAMP);

MERGE INTO SENDER_TYPES target
USING (SELECT '82000000-0000-0000-0000-000000000002' ID, 'Agente IA' NAME FROM DUAL) source
ON (target.SENDER_TYPES_ID = source.ID)
WHEN MATCHED THEN UPDATE SET target.NAME_TYPE = source.NAME
WHEN NOT MATCHED THEN
    INSERT (SENDER_TYPES_ID, NAME_TYPE, CREATED_AT)
    VALUES (source.ID, source.NAME, SYSTIMESTAMP);

MERGE INTO SENDER_TYPES target
USING (SELECT '82000000-0000-0000-0000-000000000003' ID, 'Agente humano' NAME FROM DUAL) source
ON (target.SENDER_TYPES_ID = source.ID)
WHEN MATCHED THEN UPDATE SET target.NAME_TYPE = source.NAME
WHEN NOT MATCHED THEN
    INSERT (SENDER_TYPES_ID, NAME_TYPE, CREATED_AT)
    VALUES (source.ID, source.NAME, SYSTIMESTAMP);

MERGE INTO SENDER_TYPES target
USING (SELECT '82000000-0000-0000-0000-000000000004' ID, 'Sistema' NAME FROM DUAL) source
ON (target.SENDER_TYPES_ID = source.ID)
WHEN MATCHED THEN UPDATE SET target.NAME_TYPE = source.NAME
WHEN NOT MATCHED THEN
    INSERT (SENDER_TYPES_ID, NAME_TYPE, CREATED_AT)
    VALUES (source.ID, source.NAME, SYSTIMESTAMP);

COMMIT;
