-- =============================================================================
-- VERIFICACIÓN TOTAL DE CATÁLOGOS, SEGURIDAD Y DATOS OPERACIONALES
-- Base de datos: Oracle Database
-- =============================================================================

SET PAGESIZE 150;
SET LINESIZE 220;
SET FEEDBACK ON;

PROMPT =========================================================================
PROMPT 1. AUDITORÍA DE SEGURIDAD Y ROLES
PROMPT =========================================================================

-- A. Confirmar existencia de los 6 roles canónicos
SELECT COUNT(*) AS CANONICAL_ROLES_COUNT 
FROM ROLES
WHERE ROLE_ID IN (
    '99999999-9999-9999-9999-999999999999', -- SuperAdmin
    '11111111-1111-1111-1111-111111111111', -- Administrador
    '44444444-4444-4444-4444-444444444444', -- Veterinario
    '55555555-5555-5555-5555-555555555555', -- Recepcionista
    '66666666-6666-6666-6666-666666666666', -- Auxiliar
    '77777777-7777-7777-7777-777777777777'  -- Cliente
);

-- B. Regla de negocio: El rol Cliente NUNCA debe tener permisos web (Esperado: 0)
SELECT COUNT(*) AS CLIENT_WEB_PERMISSIONS_COUNT
FROM ROLE_PERMISSIONS
WHERE ROLE_ID = '77777777-7777-7777-7777-777777777777';

-- C. Regla de seguridad: Ningún usuario con rol Cliente debe tener cuenta de login (Esperado: 0)
SELECT COUNT(*) AS CLIENTS_WITH_LOGIN_ACCOUNT
FROM USER_ACCOUNTS ua
JOIN USERS u ON ua.USER_ID = u.USER_ID
JOIN ROLES r ON u.ROLE_ID = r.ROLE_ID
WHERE UPPER(r.NAME) = 'CLIENTE';

PROMPT 
PROMPT =========================================================================
PROMPT 2. RESUMEN GLOBAL DE REGISTROS (CONTEOS)
PROMPT =========================================================================

SELECT 
    (SELECT COUNT(*) FROM ROLES) AS ROLES,
    (SELECT COUNT(*) FROM MODULES) AS MODULES,
    (SELECT COUNT(*) FROM ROLE_PERMISSIONS) AS PERMISSIONS,
    (SELECT COUNT(*) FROM USERS) AS USERS,
    (SELECT COUNT(*) FROM USER_ACCOUNTS) AS ACCOUNTS,
    (SELECT COUNT(*) FROM USER_CREDENTIALS) AS CREDENTIALS,
    (SELECT COUNT(*) FROM CLIENTS) AS CLIENTS,
    (SELECT COUNT(*) FROM VETERINARIANS) AS VETS,
    (SELECT COUNT(*) FROM PETS) AS PETS,
    (SELECT COUNT(*) FROM CLIENTS_PETS) AS CLIENTS_PETS,
    (SELECT COUNT(*) FROM APPOINTMENTS) AS APPOINTMENTS,
    (SELECT COUNT(*) FROM MEDICAL_RECORDS) AS MED_RECORDS,
    (SELECT COUNT(*) FROM VACCINATIONS) AS VACCINES
FROM DUAL;

SELECT
    (SELECT COUNT(*) FROM SPECIES) AS SPECIES,
    (SELECT COUNT(*) FROM RACES) AS RACES,
    (SELECT COUNT(*) FROM SPECIALTIES) AS SPECIALTIES,
    (SELECT COUNT(*) FROM TYPE_SERVICES) AS TYPE_SERVICES,
    (SELECT COUNT(*) FROM SERVICES) AS SERVICES,
    (SELECT COUNT(*) FROM DIAGNOSTICS) AS DIAGNOSTICS,
    (SELECT COUNT(*) FROM STATUS_APPOINTMENTS) AS APPT_STATUSES,
    (SELECT COUNT(*) FROM AVAILABILITIES) AS AVAILABILITIES,
    (SELECT COUNT(*) FROM CONVERSATIONS_STATUSES) AS CONV_STATUSES,
    (SELECT COUNT(*) FROM SENDER_TYPES) AS SENDER_TYPES,
    (SELECT COUNT(*) FROM MESSAGE_TYPES) AS MESSAGE_TYPES,
    (SELECT COUNT(*) FROM PRIORITY) AS PRIORITIES,
    (SELECT COUNT(*) FROM ESCALATIONS_STATUSES) AS ESCALATION_STATUSES,
    (SELECT COUNT(*) FROM AI_RUNS_STATUSES) AS AI_RUN_STATUSES
FROM DUAL;

PROMPT 
PROMPT =========================================================================
PROMPT 3. DETALLE DE USUARIOS, CUENTAS Y ACCESO AL SISTEMA
PROMPT =========================================================================

SELECT 
    u.EMAIL,
    r.NAME AS ROL,
    u.FULL_NAME,
    NVL(ua.USERNAME, '[SIN CUENTA]') AS USERNAME,
    NVL(ua.STATUS, '[INACTIVO]') AS ESTADO_CUENTA,
    CASE WHEN uc.PASSWORD_HASH IS NOT NULL THEN 'SI' ELSE 'NO' END AS TIENE_PASSWORD
FROM USERS u
JOIN ROLES r ON u.ROLE_ID = r.ROLE_ID
LEFT JOIN USER_ACCOUNTS ua ON u.USER_ID = ua.USER_ID
LEFT JOIN USER_CREDENTIALS uc ON ua.ACCOUNT_ID = uc.ACCOUNT_ID
ORDER BY r.NAME, u.EMAIL;

PROMPT 
PROMPT =========================================================================
PROMPT 4. DETALLE DE MASCOTAS Y DUEÑOS ASOCIADOS
PROMPT =========================================================================

SELECT 
    c.IDENTIFICATION_NUMBER AS CEDULA_DUENO,
    u.FULL_NAME AS NOMBRE_DUENO,
    p.NAME AS MASCOTA,
    s.NAME AS ESPECIE,
    NVL(r.NAME, 'No especificada') AS RAZA,
    cp.IS_PRIMARY_OWNER AS DUENO_PPAL
FROM CLIENTS_PETS cp
JOIN CLIENTS c ON cp.CLIENT_ID = c.CLIENT_ID
JOIN USERS u ON c.USER_ID = u.USER_ID
JOIN PETS p ON cp.PET_ID = p.PET_ID
JOIN SPECIES s ON p.SPECIES_ID = s.SPECIES_ID
LEFT JOIN RACES r ON p.RACE_ID = r.RACE_ID
ORDER BY u.FULL_NAME, p.NAME;

PROMPT 
PROMPT =========================================================================
PROMPT 5. DETALLE DE CITAS MÉDICAS REGISTRADAS
PROMPT =========================================================================

SELECT 
    a.APPOINTMENT_ID,
    TO_CHAR(a.SCHEDULED_START, 'YYYY-MM-DD HH24:MI') AS FECHA_HORA,
    p.NAME AS MASCOTA,
    u_vet.FULL_NAME AS VETERINARIO,
    srv.NAME AS SERVICIO,
    sa.NAME AS ESTADO_CITA,
    a.REQUESTER_PHONE_NUMBER AS TELEFONO
FROM APPOINTMENTS a
JOIN CLIENTS_PETS cp ON a.CLIENT_PET_ID = cp.CLIENT_PET_ID
JOIN PETS p ON cp.PET_ID = p.PET_ID
JOIN VETERINARIANS v ON a.VETERINARIAN_ID = v.VETERINARIAN_ID
JOIN USERS u_vet ON v.USER_ID = u_vet.USER_ID
JOIN SERVICES srv ON a.SERVICE_ID = srv.SERVICE_ID
JOIN STATUS_APPOINTMENTS sa ON a.STATUS_ID = sa.STATUS_APPOINTMENT_ID
ORDER BY a.SCHEDULED_START DESC;

PROMPT 
PROMPT =========================================================================
PROMPT 6. DETALLE DE HISTORIAS CLÍNICAS Y VACUNACIÓN
PROMPT =========================================================================

SELECT 
    mr.RECORD_ID,
    p.NAME AS MASCOTA,
    d.NAME AS DIAGNOSTICO,
    mr.WEIGHT_AT_VISIT AS PESO_KG,
    mr.TEMPERATURE AS TEMP_C,
    mr.TREATMENT AS TRATAMIENTO,
    NVL(v.VACCINE_NAME, 'Sin vacuna') AS VACUNA_APLICADA
FROM MEDICAL_RECORDS mr
JOIN CLIENTS_PETS cp ON mr.CLIENT_PET_ID = cp.CLIENT_PET_ID
JOIN PETS p ON cp.PET_ID = p.PET_ID
JOIN DIAGNOSTICS d ON mr.DIAGNOSTIC_ID = d.ID
LEFT JOIN VACCINATIONS v ON mr.RECORD_ID = v.RECORD_ID
ORDER BY p.NAME;

PROMPT =========================================================================
PROMPT FIN DE LA VERIFICACIÓN
PROMPT =========================================================================