-- Parche Oracle: vincula RACES.SPECIES_ID (si la columna no existe, la crea).
-- Ejecutar con el usuario del esquema de la app. Idempotente en lo posible.

SET DEFINE OFF;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'RACES' AND COLUMN_NAME = 'SPECIES_ID';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RACES ADD (SPECIES_ID VARCHAR2(36))';
  END IF;
END;
/

UPDATE RACES r
SET SPECIES_ID = (
    SELECT s.SPECIES_ID FROM SPECIES s
    WHERE UPPER(s.NAME) IN ('FELINO', 'GATO') AND ROWNUM = 1
)
WHERE r.SPECIES_ID IS NULL
  AND (
       UPPER(r.NAME) LIKE '%SIAM%'
    OR UPPER(r.NAME) LIKE '%PERSA%'
    OR UPPER(r.NAME) LIKE '%ANGORA%'
    OR UPPER(r.NAME) LIKE '%BENGAL%'
    OR UPPER(r.NAME) LIKE '%MAINE%'
    OR UPPER(r.NAME) LIKE '%RAGDOLL%'
    OR UPPER(r.NAME) LIKE '%SPHYNX%'
  );

UPDATE RACES r
SET SPECIES_ID = (
    SELECT s.SPECIES_ID FROM SPECIES s
    WHERE UPPER(s.NAME) IN ('CANINO', 'PERRO') AND ROWNUM = 1
)
WHERE r.SPECIES_ID IS NULL
  AND (
       UPPER(r.NAME) LIKE '%GOLDEN%'
    OR UPPER(r.NAME) LIKE '%PASTOR%'
    OR UPPER(r.NAME) LIKE '%LABRADOR%'
    OR UPPER(r.NAME) LIKE '%BULLDOG%'
    OR UPPER(r.NAME) LIKE '%BEAGLE%'
    OR UPPER(r.NAME) LIKE '%HUSKY%'
    OR UPPER(r.NAME) LIKE '%POODLE%'
    OR UPPER(r.NAME) LIKE '%TERRIER%'
  );

UPDATE RACES r
SET SPECIES_ID = (
    SELECT s.SPECIES_ID FROM SPECIES s
    WHERE UPPER(s.NAME) = 'CONEJO' AND ROWNUM = 1
)
WHERE r.SPECIES_ID IS NULL
  AND (
       UPPER(r.NAME) LIKE '%HOLAND%'
    OR UPPER(r.NAME) LIKE '%REX%'
    OR UPPER(r.NAME) LIKE '%LEON%'
    OR UPPER(r.NAME) LIKE '%ENANO%'
  );

UPDATE RACES r
SET SPECIES_ID = NVL(
    (SELECT s.SPECIES_ID FROM SPECIES s WHERE UPPER(s.NAME) IN ('CANINO', 'PERRO') AND ROWNUM = 1),
    (SELECT s.SPECIES_ID FROM SPECIES s WHERE ROWNUM = 1)
)
WHERE r.SPECIES_ID IS NULL;

ALTER TABLE RACES MODIFY (SPECIES_ID VARCHAR2(36) NOT NULL);

BEGIN
  EXECUTE IMMEDIATE
    'ALTER TABLE RACES ADD CONSTRAINT FK_RACES_SPECIES FOREIGN KEY (SPECIES_ID) REFERENCES SPECIES (SPECIES_ID)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2275 THEN RAISE; END IF;
END;
/

COMMIT;
