SET DEFINE OFF
SET SERVEROUTPUT ON
ALTER SESSION SET CONTAINER = FREEPDB1;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_TAB_COLUMNS
   WHERE OWNER = 'TOMDEVV' AND TABLE_NAME = 'PETS' AND COLUMN_NAME = 'PHOTO_URL';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TOMDEVV.PETS ADD (PHOTO_URL NVARCHAR2(500))';
    DBMS_OUTPUT.PUT_LINE('OK: PHOTO_URL creada');
  ELSE
    DBMS_OUTPUT.PUT_LINE('OK: PHOTO_URL ya existia');
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
    FROM TOMDEVV."__EFMigrationsHistory"
   WHERE "MigrationId" = '20260908150000_AddPetPhotoUrl';
  IF v_count = 0 THEN
    INSERT INTO TOMDEVV."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260908150000_AddPetPhotoUrl', '10.0.0');
    DBMS_OUTPUT.PUT_LINE('OK: migration history');
  END IF;
END;
/

COMMIT;
SELECT 'HAS_PHOTO_URL=' || COUNT(*) FROM ALL_TAB_COLUMNS
 WHERE OWNER='TOMDEVV' AND TABLE_NAME='PETS' AND COLUMN_NAME='PHOTO_URL';
EXIT
