-- =============================================================================
-- PARCHE DDL: SEPARACIÓN DE CLIENTS Y USERS
-- Adapta la tabla CLIENTS al nuevo modelo independiente de USERS.
-- Idempotente: seguro de ejecutar múltiples veces.
-- =============================================================================

SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR CONTINUE;

DECLARE
  v_count NUMBER;
BEGIN
  -- 1. FULL_NAME
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CLIENTS' AND COLUMN_NAME = 'FULL_NAME';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CLIENTS ADD (FULL_NAME VARCHAR2(150))';
    DBMS_OUTPUT.PUT_LINE('OK: FULL_NAME added');
  END IF;

  -- 2. EMAIL
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CLIENTS' AND COLUMN_NAME = 'EMAIL';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CLIENTS ADD (EMAIL VARCHAR2(150))';
    DBMS_OUTPUT.PUT_LINE('OK: EMAIL added');
  END IF;

  -- Indice único UX_CLIENTS_EMAIL
  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'UX_CLIENTS_EMAIL';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_CLIENTS_EMAIL ON CLIENTS (EMAIL)';
    DBMS_OUTPUT.PUT_LINE('OK: UX_CLIENTS_EMAIL index created');
  END IF;

  -- 3. IS_ACTIVE
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CLIENTS' AND COLUMN_NAME = 'IS_ACTIVE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CLIENTS ADD (IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL)';
    DBMS_OUTPUT.PUT_LINE('OK: IS_ACTIVE added');
  END IF;

  -- 4. Eliminar REGISTRATION_DATE si existe
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CLIENTS' AND COLUMN_NAME = 'REGISTRATION_DATE';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CLIENTS DROP COLUMN REGISTRATION_DATE';
    DBMS_OUTPUT.PUT_LINE('OK: REGISTRATION_DATE dropped');
  END IF;

  -- 5. Eliminar restricción de clave foránea FK_CLIENTS_USERS_USER_ID si existe
  SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_CLIENTS_USERS_USER_ID';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CLIENTS DROP CONSTRAINT FK_CLIENTS_USERS_USER_ID';
    DBMS_OUTPUT.PUT_LINE('OK: FK_CLIENTS_USERS_USER_ID dropped');
  END IF;

  -- 6. Modificar USER_ID para permitir nulos si aún es NOT NULL
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CLIENTS' AND COLUMN_NAME = 'USER_ID' AND NULLABLE = 'N';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CLIENTS MODIFY (USER_ID NULL)';
    DBMS_OUTPUT.PUT_LINE('OK: USER_ID modified to NULL');
  END IF;

  -- 7. Eliminar índice único sobre USER_ID si existe
  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IX_CLIENTS_USER_ID';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX IX_CLIENTS_USER_ID';
    DBMS_OUTPUT.PUT_LINE('OK: IX_CLIENTS_USER_ID dropped');
  END IF;

  -- 8. Asegurar PHONE_NUMBER NOT NULL
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CLIENTS' AND COLUMN_NAME = 'PHONE_NUMBER' AND NULLABLE = 'Y';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CLIENTS MODIFY (PHONE_NUMBER NVARCHAR2(20) NOT NULL)';
    DBMS_OUTPUT.PUT_LINE('OK: PHONE_NUMBER modified to NOT NULL');
  END IF;
END;
/

COMMIT;
