// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(VeterinaryDbContext))]
    [Migration("20260826131945_StatusAppoinmentMigration")]
    partial class StatusAppoinmentMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Diagnostics.Entities.Diagnostic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CODE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DIAGNOSTICS", (string)null);
                });

            modelBuilder.Entity("Domain.Pets.Entities.PetEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("PET_ID");

                    b.Property<int>("Age")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AGE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("GENDER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.Property<string>("Observations")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("OBSERVATIONS");

                    b.Property<string>("RaceId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("RACE_ID");

                    b.Property<string>("SpeciesId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("SPECIES_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("NUMBER(6,3)")
                        .HasColumnName("WEIGHT");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("PETS", (string)null);
                });

            modelBuilder.Entity("Domain.Roles.Entities.Roles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ROLE_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .HasColumnType("CLOB")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ROLES", (string)null);
                });

            modelBuilder.Entity("Domain.StatusAppointments.Entities.StatusAppointment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("STATUS_APPOINTMENT_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("STATUS_APPOINTMENTS", (string)null);
                });

            modelBuilder.Entity("Domain.UserAccounts.Entities.UserAccounts", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ACCOUNT_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("MAIL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("VARCHAR2(40)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("USER_ID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USER_ACCOUNTS", (string)null);
                });

            modelBuilder.Entity("Domain.UserCredentials.Entities.UserCredentials", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CREDENTIAL_ID");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ACCOUNT_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("LastChanged")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("LAST_CHANGED");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("USER_CREDENTIALS", (string)null);
                });

            modelBuilder.Entity("Domain.Users.Entities.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("USER_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("FULL_NAME");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ROLE_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("veterinarian_backend.Domain.Races.Entities.RaceEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("RACE_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("RACES", (string)null);
                });

            modelBuilder.Entity("veterinarian_backend.Domain.Species.Entities.SpeciesEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("SPECIES_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("SPECIES", (string)null);
                });

            modelBuilder.Entity("Domain.Pets.Entities.PetEntity", b =>
                {
                    b.HasOne("veterinarian_backend.Domain.Races.Entities.RaceEntity", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("veterinarian_backend.Domain.Species.Entities.SpeciesEntity", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Domain.UserAccounts.Entities.UserAccounts", b =>
                {
                    b.HasOne("Domain.Users.Entities.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.UserCredentials.Entities.UserCredentials", b =>
                {
                    b.HasOne("Domain.UserAccounts.Entities.UserAccounts", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Users.Entities.Users", b =>
                {
                    b.HasOne("Domain.Roles.Entities.Roles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
