// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(VeterinaryDbContext))]
    [Migration("20260831150033_ChatEscalationsStatusMigration")]
    partial class ChatEscalationsStatusMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.AccountStatements.Entities.AccountStatements", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("STATEMENT_ID");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ACCOUNT_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("DATE")
                        .HasColumnName("ISSUE_DATE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("ACCOUNT_STATEMENTS", (string)null);
                });

            modelBuilder.Entity("Domain.AgentHumans.Entities.AgentHuman", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("AGENT_HUMAN_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AGENT_HUMANS", (string)null);
                });

            modelBuilder.Entity("Domain.AiModels.Entities.AiModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("AI_MODEL_ID");

                    b.Property<int>("ContextWindow")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CONTEXT_WINDOW");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<decimal>("InputTokenPrice")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("INPUT_TOKEN_PRICE");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MAX_TOKENS");

                    b.Property<string>("ModelKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("MODEL_KEY");

                    b.Property<string>("NameModel")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("NAME_MODEL");

                    b.Property<decimal>("OutputTokenPrice")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("OUTPUT_TOKEN_PRICE");

                    b.Property<string>("ProviderModelAiId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("PROVIDER_MODEL_AI_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderModelAiId");

                    b.ToTable("AI_MODELS", (string)null);
                });

            modelBuilder.Entity("Domain.AiRunStatuses.Entities.AiRunStatusEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("AI_RUNS_STATUSES_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("NameStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME_STATUS");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("AI_RUNS_STATUSES", (string)null);
                });

            modelBuilder.Entity("Domain.AppointmentStatusHistories.Entities.AppointmentStatusHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("APPOINTMENT_STATUS_ID");

                    b.Property<string>("AppointmentId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("APPOINTMENT_ID");

                    b.Property<string>("ClientPetId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CLIENT_PET_ID");

                    b.Property<string>("Comment")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("COMMENT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("STATUS_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATE_AT");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ClientPetId");

                    b.HasIndex("StatusId");

                    b.ToTable("APPOINTMENT_STATUS_HISTORIES", (string)null);
                });

            modelBuilder.Entity("Domain.Appointments.Entities.Appointment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("APPOINTMENT_ID");

                    b.Property<string>("AvailabilityId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("AVAILABILITY_ID");

                    b.Property<string>("ClientPetId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CLIENT_PET_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("NOTES");

                    b.Property<DateTime>("ScheduledEnd")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("SCHEDULED_END");

                    b.Property<DateTime>("ScheduledStart")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("SCHEDULED_START");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("SERVICE_ID");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("STATUS_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATE_AT");

                    b.Property<string>("VeterinarianId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("VETERINARIAN_ID");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("ClientPetId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StatusId");

                    b.HasIndex("VeterinarianId");

                    b.ToTable("APPOINTMENTS", (string)null);
                });

            modelBuilder.Entity("Domain.Availabilities.Entities.Availability", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("AVAILABILITY_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<decimal>("DayOfWeek")
                        .HasColumnType("NUMBER")
                        .HasColumnName("DAY_OF_WEEK");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("END_TIME");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("START_TIME");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("VeterinarianId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("VETERINARIAN_ID");

                    b.HasKey("Id");

                    b.HasIndex("VeterinarianId");

                    b.ToTable("AVAILABILITIES", (string)null);
                });

            modelBuilder.Entity("Domain.ChatAttachments.Entities.ChatAttachment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_ATTACHMENTS_ID");

                    b.Property<string>("ChatMessageId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_MESSAGES_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("FILE_NAME");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("FILE_TYPE");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR2(1000)")
                        .HasColumnName("FILE_URL");

                    b.HasKey("Id");

                    b.HasIndex("ChatMessageId")
                        .HasDatabaseName("IX_CHAT_ATTACHMENTS_CHAT_MESSAGES_ID");

                    b.ToTable("CHAT_ATTACHMENTS", (string)null);
                });

            modelBuilder.Entity("Domain.ChatConversationAiSettings.Entities.ChatConversationAiSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_CONVERSATION_AI_SETTING_ID");

                    b.Property<int>("AiEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1)
                        .HasColumnName("AI_ENABLED");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CONVERSATION_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("DefaultModelId")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("DEFAULT_MODEL_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("IX_CHAT_CONVERSATION_AI_SETTINGS_CONVERSATION_ID");

                    b.HasIndex("DefaultModelId")
                        .HasDatabaseName("IX_CHAT_CONVERSATION_AI_SETTINGS_DEFAULT_MODEL_ID");

                    b.ToTable("CHAT_CONVERSATION_AI_SETTINGS", (string)null);
                });

            modelBuilder.Entity("Domain.ChatConversationAssignments.Entities.ChatConversationAssignment", b =>
                {
                    b.Property<string>("ChatConversationId")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_CONVERSATIONS_ID");

                    b.Property<string>("AgentHumanId")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("AGENT_HUMAN_ID");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ASSIGNED_AT");

                    b.Property<DateTime?>("UnassignedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UNASSIGNED_AT");

                    b.HasKey("ChatConversationId");

                    b.HasIndex("AgentHumanId")
                        .HasDatabaseName("IX_CHAT_CONVERSATION_ASSIGNMENTS_AGENT_HUMAN_ID");

                    b.ToTable("CHAT_CONVERSATION_ASSIGNMENTS", (string)null);
                });

            modelBuilder.Entity("Domain.ChatConversations.Entities.ChatConversation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_CONVERSATIONS_ID");

                    b.Property<int>("AiEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1)
                        .HasColumnName("AI_ENABLED");

                    b.Property<int>("Closed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("CLOSED");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CLOSED_AT");

                    b.Property<string>("ClosedBy")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CLOSED_BY");

                    b.Property<string>("ConversationStatusId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CONVERSATION_STATUS_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("LAST_MESSAGE_AT");

                    b.Property<string>("PriorityId")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("PRIORITY_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationStatusId")
                        .HasDatabaseName("IX_CHAT_CONVERSATIONS_CONVERSATION_STATUS_ID");

                    b.HasIndex("PriorityId")
                        .HasDatabaseName("IX_CHAT_CONVERSATIONS_PRIORITY_ID");

                    b.ToTable("CHAT_CONVERSATIONS", (string)null);
                });

            modelBuilder.Entity("Domain.ChatEscalationAssignments.Entities.ChatEscalationAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_ESCALATION_ASSIGNMENTS_ID");

                    b.Property<string>("AgentHumanId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("AGENT_HUMAN_ID");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ASSIGNED_AT");

                    b.Property<string>("ChatEscalationId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_ESCALATIONS_ID");

                    b.HasKey("Id");

                    b.HasIndex("AgentHumanId")
                        .HasDatabaseName("IX_CHAT_ESC_ASG_AGT");

                    b.HasIndex("ChatEscalationId")
                        .HasDatabaseName("IX_CHAT_ESC_ASG_ESC");

                    b.ToTable("CHAT_ESCALATION_ASSIGNMENTS", (string)null);
                });

            modelBuilder.Entity("Domain.ChatEscalationResolutions.Entities.ChatEscalationResolution", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_ESCALATION_RESOLUTION_ID");

                    b.Property<string>("ChatEscalationId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_ESCALATIONS_ID");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("CLOB")
                        .HasColumnName("RESOLUTION_NOTE");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("RESOLVED_AT");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("RESOLVED_BY");

                    b.HasKey("Id");

                    b.HasIndex("ChatEscalationId")
                        .HasDatabaseName("IX_CHAT_ESC_RES_ESC");

                    b.ToTable("CHAT_ESCALATION_RESOLUTION", (string)null);
                });

            modelBuilder.Entity("Domain.ChatEscalationStatusHistories.Entities.ChatEscalationStatusHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_ESCALATION_STATUS_ID");

                    b.Property<string>("ChatEscalationId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_ESCALATIONS_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("EscalationStatusId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ESCALATIONS_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id")
                        .HasName("PK_CHAT_ESC_STAT_HIST");

                    b.HasIndex("ChatEscalationId")
                        .HasDatabaseName("IX_CHAT_ESC_HIST_ESC");

                    b.HasIndex("EscalationStatusId")
                        .HasDatabaseName("IX_CHAT_ESC_HIST_STA");

                    b.ToTable("CHAT_ESCALATION_STATUS_HISTORY", (string)null);
                });

            modelBuilder.Entity("Domain.ChatEscalations.Entities.ChatEscalation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_ESCALATIONS_ID");

                    b.Property<string>("ChatConversationId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_CONVERSATIONS_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("EscalationStatusId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ESCALATIONS_ID");

                    b.Property<int>("FromAi")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FROM_AI");

                    b.Property<string>("Reason")
                        .HasColumnType("CLOB")
                        .HasColumnName("REASON");

                    b.Property<string>("UpdateAt")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("UPDATE_AT");

                    b.HasKey("Id");

                    b.HasIndex("ChatConversationId")
                        .HasDatabaseName("IX_CHAT_ESC_CONV_ID");

                    b.HasIndex("EscalationStatusId")
                        .HasDatabaseName("IX_CHAT_ESC_STAT_ID");

                    b.ToTable("CHAT_ESCALATIONS", (string)null);
                });

            modelBuilder.Entity("Domain.ChatMessages.Entities.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_MESSAGES_ID");

                    b.Property<string>("ChatConversationId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_CONVERSATIONS_ID");

                    b.Property<string>("ChatParticipantId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_PARTICIPANTS_ID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("CONTENT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("MessageTypeId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("MESSAGE_TYPE_ID");

                    b.Property<string>("Metadata")
                        .HasColumnType("CLOB")
                        .HasColumnName("METADATA");

                    b.Property<string>("SenderTypesId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("SENDER_TYPES_ID");

                    b.HasKey("Id");

                    b.HasIndex("ChatConversationId")
                        .HasDatabaseName("IX_CHAT_MESSAGES_CHAT_CONVERSATIONS_ID");

                    b.HasIndex("ChatParticipantId")
                        .HasDatabaseName("IX_CHAT_MESSAGES_CHAT_PARTICIPANTS_ID");

                    b.HasIndex("MessageTypeId")
                        .HasDatabaseName("IX_CHAT_MESSAGES_MESSAGE_TYPE_ID");

                    b.HasIndex("SenderTypesId")
                        .HasDatabaseName("IX_CHAT_MESSAGES_SENDER_TYPES_ID");

                    b.ToTable("CHAT_MESSAGES", (string)null);
                });

            modelBuilder.Entity("Domain.ChatParticipants.Entities.ChatParticipant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_PARTICIPANTS_ID");

                    b.Property<string>("AgentHumanId")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("AGENT_HUMAN_ID");

                    b.Property<string>("AiModelId")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("AI_MODEL_ID");

                    b.Property<string>("ChatConversationId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_CONVERSATIONS_ID");

                    b.Property<string>("ChatUserProfileId")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_USER_PROFILE_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("ParticipantTypeId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("PARTICIPANT_TYPE_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("AgentHumanId")
                        .HasDatabaseName("IX_CHAT_PARTICIPANTS_AGENT_HUMAN_ID");

                    b.HasIndex("ChatConversationId")
                        .HasDatabaseName("IX_CHAT_PARTICIPANTS_CHAT_CONVERSATIONS_ID");

                    b.HasIndex("ChatUserProfileId")
                        .HasDatabaseName("IX_CHAT_PARTICIPANTS_CHAT_USER_PROFILE_ID");

                    b.HasIndex("ParticipantTypeId")
                        .HasDatabaseName("IX_CHAT_PARTICIPANTS_PARTICIPANT_TYPE_ID");

                    b.ToTable("CHAT_PARTICIPANTS", (string)null);
                });

            modelBuilder.Entity("Domain.ChatUserProfiles.Entities.ChatUserProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CHAT_USER_PROFILE_ID");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("AVATAR_URL");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("BIO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("DISPLAY_NAME");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_CHAT_USER_PROFILES_USER_ID");

                    b.ToTable("CHAT_USER_PROFILES", (string)null);
                });

            modelBuilder.Entity("Domain.Clients.Entities.ClientEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CLIENT_ID");

                    b.Property<string>("Address")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ADDRESS");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("IDENTIFICATION_NUMBER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REGISTRATION_DATE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATE_AT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("CLIENTS", (string)null);
                });

            modelBuilder.Entity("Domain.ClientsPets.Entities.ClientPetEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CLIENT_PET_ID");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CLIENT_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("IsPrimaryOwner")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("IS_PRIMARY_OWNER");

                    b.Property<string>("PetId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("PET_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("ClientId", "PetId")
                        .IsUnique();

                    b.ToTable("CLIENTS_PETS", (string)null);
                });

            modelBuilder.Entity("Domain.ConversationStatuses.Entities.ConversationStatusEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CONVERSATIONS_STATUSES_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME_STATUS");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("CONVERSATIONS_STATUSES", (string)null);
                });

            modelBuilder.Entity("Domain.Diagnostics.Entities.Diagnostic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CODE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DIAGNOSTICS", (string)null);
                });

            modelBuilder.Entity("Domain.EscalationStatuses.Entities.EscalationStatusEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ESCALATIONS_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME_STATUS");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("ESCALATIONS_STATUSES", (string)null);
                });

            modelBuilder.Entity("Domain.MedicalRecords.Entities.MedicalRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("RECORD_ID");

                    b.Property<string>("AppointmentId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("APPOINTMENT_ID");

                    b.Property<string>("ClientPetId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CLIENT_PET_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("DiagnosticId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("DIAGNOSTIC_ID");

                    b.Property<string>("Symptoms")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("SYMPTOMS");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TEMPERATURE");

                    b.Property<string>("Treatment")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("TREATMENT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATE_AT");

                    b.Property<decimal?>("WeightAtVisit")
                        .HasColumnType("NUMBER")
                        .HasColumnName("WEIGHT_AT_VISIT");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ClientPetId");

                    b.HasIndex("DiagnosticId");

                    b.ToTable("MEDICAL_RECORDS", (string)null);
                });

            modelBuilder.Entity("Domain.MessageTypes.Entities.MessageTypeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("MESSAGE_TYPES_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME_TYPE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("MESSAGE_TYPES", (string)null);
                });

            modelBuilder.Entity("Domain.Notifications.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("NOTIFICATION_ID");

                    b.Property<string>("AppointmentId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("APPOINTMENT_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR2(1000)")
                        .HasColumnName("MESSAGE");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("SENT_AT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TYPE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATE_AT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("UserId");

                    b.ToTable("NOTIFICATIONS", (string)null);
                });

            modelBuilder.Entity("Domain.Pets.Entities.PetEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("PET_ID");

                    b.Property<int>("Age")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AGE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("GENDER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.Property<string>("Observations")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("OBSERVATIONS");

                    b.Property<string>("RaceId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("RACE_ID");

                    b.Property<string>("SpeciesId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("SPECIES_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("NUMBER(6,3)")
                        .HasColumnName("WEIGHT");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("PETS", (string)null);
                });

            modelBuilder.Entity("Domain.Priorities.Entities.PriorityEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("PRIORITY_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME_PRIORITY");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("PRIORITY", (string)null);
                });

            modelBuilder.Entity("Domain.ProviderModelsAi.Entities.ProviderModelAi", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("PROVIDER_MODEL_AI_ID");

                    b.Property<string>("BusinessName")
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("BUSINESS_NAME");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("NameProviderAi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("NAME_PROVIDER_AI");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("Website")
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("WEBSITE");

                    b.HasKey("Id");

                    b.ToTable("PROVIDER_MODELS_AI", (string)null);
                });

            modelBuilder.Entity("Domain.Races.Entities.RaceEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("RACE_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("RACES", (string)null);
                });

            modelBuilder.Entity("Domain.Roles.Entities.Roles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ROLE_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .HasColumnType("CLOB")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ROLES", (string)null);
                });

            modelBuilder.Entity("Domain.SenderTypes.Entities.SenderTypeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("SENDER_TYPES_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME_TYPE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("SENDER_TYPES", (string)null);
                });

            modelBuilder.Entity("Domain.Services.Entities.Service", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("SERVICE_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<decimal>("DurationMinutes")
                        .HasColumnType("NUMBER")
                        .HasColumnName("DURATION_MINUTES");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMBER")
                        .HasColumnName("PRICE");

                    b.Property<string>("TypeServiceId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("TYPE_SERVICE_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATE_AT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TypeServiceId");

                    b.ToTable("SERVICES", (string)null);
                });

            modelBuilder.Entity("Domain.Specialties.Entities.SpecialtyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("SPECIALTY_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SPECIALTIES", (string)null);
                });

            modelBuilder.Entity("Domain.Species.Entities.SpeciesEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("SPECIES_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("SPECIES", (string)null);
                });

            modelBuilder.Entity("Domain.StatusAppointments.Entities.StatusAppointment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("STATUS_APPOINTMENT_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("STATUS_APPOINTMENTS", (string)null);
                });

            modelBuilder.Entity("Domain.TypeServices.Entities.TypeService", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("TYPE_SERVICE_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TYPE_SERVICES", (string)null);
                });

            modelBuilder.Entity("Domain.UserAccounts.Entities.UserAccounts", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ACCOUNT_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("MAIL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("VARCHAR2(40)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("USER_ID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USER_ACCOUNTS", (string)null);
                });

            modelBuilder.Entity("Domain.UserCredentials.Entities.UserCredentials", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CREDENTIAL_ID");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ACCOUNT_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("LastChanged")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("LAST_CHANGED");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("USER_CREDENTIALS", (string)null);
                });

            modelBuilder.Entity("Domain.UserTokens.Entities.UserTokens", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("TOKEN_ID");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ACCOUNT_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("EXPIRES_AT");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TOKEN_TYPE");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("TOKEN_VALUE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TokenValue")
                        .IsUnique();

                    b.ToTable("USER_TOKENS", (string)null);
                });

            modelBuilder.Entity("Domain.Users.Entities.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("USER_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("FULL_NAME");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ROLE_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("Domain.Vaccinations.Entities.Vaccination", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("VACCINATION_ID");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("DATE")
                        .HasColumnName("APPLICATION_DATE");

                    b.Property<string>("ClientPetId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CLIENT_PET_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<decimal>("DoseNumber")
                        .HasColumnType("NUMBER")
                        .HasColumnName("DOSE_NUMBER");

                    b.Property<DateTime?>("NextDoseDate")
                        .HasColumnType("DATE")
                        .HasColumnName("NEXT_DOSE_DATE");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("RECORD_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATE_AT");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("VACCINE_NAME");

                    b.HasKey("Id");

                    b.HasIndex("ClientPetId");

                    b.HasIndex("RecordId");

                    b.ToTable("VACCINATIONS", (string)null);
                });

            modelBuilder.Entity("Domain.Veterinarians.Entities.Veterinarian", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("VETERINARIAN_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("LICENSE_NUMBER");

                    b.Property<string>("SpecialtyId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("SPECIALTY_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("UserId");

                    b.ToTable("VETERINARIANS", (string)null);
                });

            modelBuilder.Entity("Domain.AccountStatements.Entities.AccountStatements", b =>
                {
                    b.HasOne("Domain.UserAccounts.Entities.UserAccounts", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.AgentHumans.Entities.AgentHuman", b =>
                {
                    b.HasOne("Domain.Users.Entities.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.AiModels.Entities.AiModel", b =>
                {
                    b.HasOne("Domain.ProviderModelsAi.Entities.ProviderModelAi", null)
                        .WithMany()
                        .HasForeignKey("ProviderModelAiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.AppointmentStatusHistories.Entities.AppointmentStatusHistory", b =>
                {
                    b.HasOne("Domain.Appointments.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.ClientsPets.Entities.ClientPetEntity", "ClientPet")
                        .WithMany()
                        .HasForeignKey("ClientPetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.StatusAppointments.Entities.StatusAppointment", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("ClientPet");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Domain.Appointments.Entities.Appointment", b =>
                {
                    b.HasOne("Domain.Availabilities.Entities.Availability", "Availability")
                        .WithMany()
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.ClientsPets.Entities.ClientPetEntity", "ClientPet")
                        .WithMany()
                        .HasForeignKey("ClientPetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Services.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.StatusAppointments.Entities.StatusAppointment", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Veterinarians.Entities.Veterinarian", "Veterinarian")
                        .WithMany()
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Availability");

                    b.Navigation("ClientPet");

                    b.Navigation("Service");

                    b.Navigation("Status");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("Domain.Availabilities.Entities.Availability", b =>
                {
                    b.HasOne("Domain.Veterinarians.Entities.Veterinarian", "Veterinarian")
                        .WithMany()
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("Domain.ChatAttachments.Entities.ChatAttachment", b =>
                {
                    b.HasOne("Domain.ChatMessages.Entities.ChatMessage", null)
                        .WithMany()
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHAT_ATTACHMENTS_CHAT_MESSAGES_CHAT_MESSAGES_ID");
                });

            modelBuilder.Entity("Domain.ChatConversationAiSettings.Entities.ChatConversationAiSetting", b =>
                {
                    b.HasOne("Domain.ChatConversations.Entities.ChatConversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHAT_CONVERSATION_AI_SETTINGS_CHAT_CONVERSATIONS_CONVERSATION_ID");

                    b.HasOne("Domain.AiModels.Entities.AiModel", null)
                        .WithMany()
                        .HasForeignKey("DefaultModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CHAT_CONVERSATION_AI_SETTINGS_AI_MODELS_DEFAULT_MODEL_ID");
                });

            modelBuilder.Entity("Domain.ChatConversationAssignments.Entities.ChatConversationAssignment", b =>
                {
                    b.HasOne("Domain.AgentHumans.Entities.AgentHuman", null)
                        .WithMany()
                        .HasForeignKey("AgentHumanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CHAT_CONVERSATION_ASSIGNMENTS_AGENT_HUMANS_AGENT_HUMAN_ID");

                    b.HasOne("Domain.ChatConversations.Entities.ChatConversation", null)
                        .WithOne()
                        .HasForeignKey("Domain.ChatConversationAssignments.Entities.ChatConversationAssignment", "ChatConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHAT_CONVERSATION_ASSIGNMENTS_CHAT_CONVERSATIONS_CHAT_CONVERSATIONS_ID");
                });

            modelBuilder.Entity("Domain.ChatConversations.Entities.ChatConversation", b =>
                {
                    b.HasOne("Domain.ConversationStatuses.Entities.ConversationStatusEntity", null)
                        .WithMany()
                        .HasForeignKey("ConversationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHAT_CONVERSATIONS_CONVERSATIONS_STATUSES_CONVERSATION_STATUS_ID");

                    b.HasOne("Domain.Priorities.Entities.PriorityEntity", null)
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CHAT_CONVERSATIONS_PRIORITY_PRIORITY_ID");
                });

            modelBuilder.Entity("Domain.ChatEscalationAssignments.Entities.ChatEscalationAssignment", b =>
                {
                    b.HasOne("Domain.AgentHumans.Entities.AgentHuman", null)
                        .WithMany()
                        .HasForeignKey("AgentHumanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHAT_ESC_ASG_AGT");

                    b.HasOne("Domain.ChatEscalations.Entities.ChatEscalation", null)
                        .WithMany()
                        .HasForeignKey("ChatEscalationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHAT_ESC_ASG_ESC");
                });

            modelBuilder.Entity("Domain.ChatEscalationResolutions.Entities.ChatEscalationResolution", b =>
                {
                    b.HasOne("Domain.ChatEscalations.Entities.ChatEscalation", null)
                        .WithMany()
                        .HasForeignKey("ChatEscalationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHAT_ESC_RES_ESC");
                });

            modelBuilder.Entity("Domain.ChatEscalationStatusHistories.Entities.ChatEscalationStatusHistory", b =>
                {
                    b.HasOne("Domain.ChatEscalations.Entities.ChatEscalation", null)
                        .WithMany()
                        .HasForeignKey("ChatEscalationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHAT_ESC_HIST_ESC");

                    b.HasOne("Domain.EscalationStatuses.Entities.EscalationStatusEntity", null)
                        .WithMany()
                        .HasForeignKey("EscalationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHAT_ESC_HIST_STA");
                });

            modelBuilder.Entity("Domain.ChatEscalations.Entities.ChatEscalation", b =>
                {
                    b.HasOne("Domain.ChatConversations.Entities.ChatConversation", null)
                        .WithMany()
                        .HasForeignKey("ChatConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHAT_ESC_CONV_ID");

                    b.HasOne("Domain.EscalationStatuses.Entities.EscalationStatusEntity", null)
                        .WithMany()
                        .HasForeignKey("EscalationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHAT_ESC_STAT_ID");
                });

            modelBuilder.Entity("Domain.ChatMessages.Entities.ChatMessage", b =>
                {
                    b.HasOne("Domain.ChatConversations.Entities.ChatConversation", null)
                        .WithMany()
                        .HasForeignKey("ChatConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHAT_MESSAGES_CHAT_CONVERSATIONS_CHAT_CONVERSATIONS_ID");

                    b.HasOne("Domain.ChatParticipants.Entities.ChatParticipant", null)
                        .WithMany()
                        .HasForeignKey("ChatParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHAT_MESSAGES_CHAT_PARTICIPANTS_CHAT_PARTICIPANTS_ID");

                    b.HasOne("Domain.MessageTypes.Entities.MessageTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("MessageTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHAT_MESSAGES_MESSAGE_TYPES_MESSAGE_TYPE_ID");

                    b.HasOne("Domain.SenderTypes.Entities.SenderTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("SenderTypesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHAT_MESSAGES_SENDER_TYPES_SENDER_TYPES_ID");
                });

            modelBuilder.Entity("Domain.ChatParticipants.Entities.ChatParticipant", b =>
                {
                    b.HasOne("Domain.AgentHumans.Entities.AgentHuman", null)
                        .WithMany()
                        .HasForeignKey("AgentHumanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CHAT_PARTICIPANTS_AGENT_HUMANS_AGENT_HUMAN_ID");

                    b.HasOne("Domain.ChatConversations.Entities.ChatConversation", null)
                        .WithMany()
                        .HasForeignKey("ChatConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHAT_PARTICIPANTS_CHAT_CONVERSATIONS_CHAT_CONVERSATIONS_ID");

                    b.HasOne("Domain.ChatUserProfiles.Entities.ChatUserProfile", null)
                        .WithMany()
                        .HasForeignKey("ChatUserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CHAT_PARTICIPANTS_CHAT_USER_PROFILES_CHAT_USER_PROFILE_ID");

                    b.HasOne("Domain.SenderTypes.Entities.SenderTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("ParticipantTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHAT_PARTICIPANTS_SENDER_TYPES_PARTICIPANT_TYPE_ID");
                });

            modelBuilder.Entity("Domain.ChatUserProfiles.Entities.ChatUserProfile", b =>
                {
                    b.HasOne("Domain.Users.Entities.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHAT_USER_PROFILES_USERS_USER_ID");
                });

            modelBuilder.Entity("Domain.Clients.Entities.ClientEntity", b =>
                {
                    b.HasOne("Domain.Users.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.ClientsPets.Entities.ClientPetEntity", b =>
                {
                    b.HasOne("Domain.Clients.Entities.ClientEntity", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Pets.Entities.PetEntity", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Domain.MedicalRecords.Entities.MedicalRecord", b =>
                {
                    b.HasOne("Domain.Appointments.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.ClientsPets.Entities.ClientPetEntity", "ClientPet")
                        .WithMany()
                        .HasForeignKey("ClientPetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Diagnostics.Entities.Diagnostic", "Diagnostic")
                        .WithMany()
                        .HasForeignKey("DiagnosticId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("ClientPet");

                    b.Navigation("Diagnostic");
                });

            modelBuilder.Entity("Domain.Notifications.Entities.Notification", b =>
                {
                    b.HasOne("Domain.Appointments.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Users.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Pets.Entities.PetEntity", b =>
                {
                    b.HasOne("Domain.Races.Entities.RaceEntity", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Species.Entities.SpeciesEntity", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Domain.Services.Entities.Service", b =>
                {
                    b.HasOne("Domain.TypeServices.Entities.TypeService", "TypeService")
                        .WithMany()
                        .HasForeignKey("TypeServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TypeService");
                });

            modelBuilder.Entity("Domain.UserAccounts.Entities.UserAccounts", b =>
                {
                    b.HasOne("Domain.Users.Entities.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.UserCredentials.Entities.UserCredentials", b =>
                {
                    b.HasOne("Domain.UserAccounts.Entities.UserAccounts", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.UserTokens.Entities.UserTokens", b =>
                {
                    b.HasOne("Domain.UserAccounts.Entities.UserAccounts", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Users.Entities.Users", b =>
                {
                    b.HasOne("Domain.Roles.Entities.Roles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Vaccinations.Entities.Vaccination", b =>
                {
                    b.HasOne("Domain.ClientsPets.Entities.ClientPetEntity", "ClientPet")
                        .WithMany()
                        .HasForeignKey("ClientPetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.MedicalRecords.Entities.MedicalRecord", "Record")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientPet");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("Domain.Veterinarians.Entities.Veterinarian", b =>
                {
                    b.HasOne("Domain.Specialties.Entities.SpecialtyEntity", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Users.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialty");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
