// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(VeterinaryDbContext))]
    partial class VeterinaryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.AiModels.Entities.AiModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("AI_MODEL_ID");

                    b.Property<int>("ContextWindow")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CONTEXT_WINDOW");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<decimal>("InputTokenPrice")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("INPUT_TOKEN_PRICE");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MAX_TOKENS");

                    b.Property<string>("ModelKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("MODEL_KEY");

                    b.Property<string>("NameModel")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("NAME_MODEL");

                    b.Property<decimal>("OutputTokenPrice")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("OUTPUT_TOKEN_PRICE");

                    b.Property<string>("ProviderModelAiId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("PROVIDER_MODEL_AI_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderModelAiId");

                    b.ToTable("AI_MODELS", (string)null);
                });

            modelBuilder.Entity("Domain.AiRunStatuses.Entities.AiRunStatusEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("AI_RUNS_STATUSES_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("NameStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME_STATUS");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("AI_RUNS_STATUSES", (string)null);
                });

            modelBuilder.Entity("Domain.Clients.Entities.ClientEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CLIENT_ID");

                    b.Property<string>("Address")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ADDRESS");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("IDENTIFICATION_NUMBER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REGISTRATION_DATE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATE_AT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("CLIENTS", (string)null);
                });

            modelBuilder.Entity("Domain.ClientsPets.Entities.ClientPetEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CLIENT_PET_ID");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CLIENT_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("IsPrimaryOwner")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("IS_PRIMARY_OWNER");

                    b.Property<string>("PetId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("PET_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("ClientId", "PetId")
                        .IsUnique();

                    b.ToTable("CLIENTS_PETS", (string)null);
                });

            modelBuilder.Entity("Domain.ConversationStatuses.Entities.ConversationStatusEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CONVERSATIONS_STATUSES_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME_STATUS");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("CONVERSATIONS_STATUSES", (string)null);
                });

            modelBuilder.Entity("Domain.Diagnostics.Entities.Diagnostic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("CODE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DIAGNOSTICS", (string)null);
                });

            modelBuilder.Entity("Domain.Pets.Entities.PetEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("PET_ID");

                    b.Property<int>("Age")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AGE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("GENDER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.Property<string>("Observations")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("OBSERVATIONS");

                    b.Property<string>("RaceId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("RACE_ID");

                    b.Property<string>("SpeciesId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("SPECIES_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("NUMBER(6,3)")
                        .HasColumnName("WEIGHT");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("PETS", (string)null);
                });

            modelBuilder.Entity("Domain.Priorities.Entities.PriorityEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("PRIORITY_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME_PRIORITY");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("PRIORITY", (string)null);
                });

            modelBuilder.Entity("Domain.ProviderModelsAi.Entities.ProviderModelAi", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("PROVIDER_MODEL_AI_ID");

                    b.Property<string>("BusinessName")
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("BUSINESS_NAME");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("NameProviderAi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("NAME_PROVIDER_AI");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("Website")
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("WEBSITE");

                    b.HasKey("Id");

                    b.ToTable("PROVIDER_MODELS_AI", (string)null);
                });

            modelBuilder.Entity("Domain.Races.Entities.RaceEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("RACE_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("RACES", (string)null);
                });

            modelBuilder.Entity("Domain.Roles.Entities.Roles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ROLE_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .HasColumnType("CLOB")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ROLES", (string)null);
                });

            modelBuilder.Entity("Domain.SenderTypes.Entities.SenderTypeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("SENDER_TYPES_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME_TYPE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("SENDER_TYPES", (string)null);
                });

            modelBuilder.Entity("Domain.Services.Entities.Service", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("SERVICE_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<decimal>("DurationMinutes")
                        .HasColumnType("NUMBER")
                        .HasColumnName("DURATION_MINUTES");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMBER")
                        .HasColumnName("PRICE");

                    b.Property<string>("TypeServiceId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("TYPE_SERVICE_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATE_AT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TypeServiceId");

                    b.ToTable("SERVICES", (string)null);
                });

            modelBuilder.Entity("Domain.Specialties.Entities.SpecialtyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("SPECIALTY_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SPECIALTIES", (string)null);
                });

            modelBuilder.Entity("Domain.Species.Entities.SpeciesEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("SPECIES_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("SPECIES", (string)null);
                });

            modelBuilder.Entity("Domain.StatusAppointments.Entities.StatusAppointment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("STATUS_APPOINTMENT_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("STATUS_APPOINTMENTS", (string)null);
                });

            modelBuilder.Entity("Domain.TypeServices.Entities.TypeService", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("TYPE_SERVICE_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TYPE_SERVICES", (string)null);
                });

            modelBuilder.Entity("Domain.UserAccounts.Entities.UserAccounts", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ACCOUNT_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("MAIL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("VARCHAR2(40)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("USER_ID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USER_ACCOUNTS", (string)null);
                });

            modelBuilder.Entity("Domain.UserCredentials.Entities.UserCredentials", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CREDENTIAL_ID");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ACCOUNT_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("LastChanged")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("LAST_CHANGED");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("USER_CREDENTIALS", (string)null);
                });

            modelBuilder.Entity("Domain.UserTokens.Entities.UserTokens", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("TOKEN_ID");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ACCOUNT_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("EXPIRES_AT");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TOKEN_TYPE");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("TOKEN_VALUE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TokenValue")
                        .IsUnique();

                    b.ToTable("USER_TOKENS", (string)null);
                });

            modelBuilder.Entity("Domain.Users.Entities.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("USER_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("FULL_NAME");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ROLE_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("Domain.Veterinarians.Entities.Veterinarian", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("VETERINARIAN_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("LICENSE_NUMBER");

                    b.Property<string>("SpecialtyId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("SPECIALTY_ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("UserId");

                    b.ToTable("VETERINARIANS", (string)null);
                });

            modelBuilder.Entity("Domain.AiModels.Entities.AiModel", b =>
                {
                    b.HasOne("Domain.ProviderModelsAi.Entities.ProviderModelAi", null)
                        .WithMany()
                        .HasForeignKey("ProviderModelAiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Clients.Entities.ClientEntity", b =>
                {
                    b.HasOne("Domain.Users.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.ClientsPets.Entities.ClientPetEntity", b =>
                {
                    b.HasOne("Domain.Clients.Entities.ClientEntity", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Pets.Entities.PetEntity", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Domain.Pets.Entities.PetEntity", b =>
                {
                    b.HasOne("Domain.Races.Entities.RaceEntity", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Species.Entities.SpeciesEntity", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Domain.Services.Entities.Service", b =>
                {
                    b.HasOne("Domain.TypeServices.Entities.TypeService", "TypeService")
                        .WithMany()
                        .HasForeignKey("TypeServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TypeService");
                });

            modelBuilder.Entity("Domain.UserAccounts.Entities.UserAccounts", b =>
                {
                    b.HasOne("Domain.Users.Entities.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.UserCredentials.Entities.UserCredentials", b =>
                {
                    b.HasOne("Domain.UserAccounts.Entities.UserAccounts", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.UserTokens.Entities.UserTokens", b =>
                {
                    b.HasOne("Domain.UserAccounts.Entities.UserAccounts", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Users.Entities.Users", b =>
                {
                    b.HasOne("Domain.Roles.Entities.Roles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Veterinarians.Entities.Veterinarian", b =>
                {
                    b.HasOne("Domain.Specialties.Entities.SpecialtyEntity", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Users.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialty");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
